PROFILE = {
    'name': 'Srinjoy Ghosh',
    'role': 'AI/ML Engineer & Researcher',
    'location': 'Nuremberg, Germany',
    'email': 'ghoshsrinjoy97@gmail.com',
    'phone': '+49 15560812680',
    'github': 'https://github.com/GhoshSrinjoy',
    'linkedin': 'https://www.linkedin.com/in/srinjoy-ghosh-224852185/',
    'intro': 'Deploying intelligent agents. Optimizing AI models. Building systems that work in the real world.',
    'bio': 'I build intelligent systems, from AI agents and retrieval pipelines to tools that make machine learning easier to understand. My work brings together over five years of engineering experience, applied research, and hands-on experimentation.',
}

# Content is grounded in the original portfolio and the linked project READMEs.
PROJECTS = [
    dict(name='LinkedIn Jobs MCP Server', repo='linkedin-job-mcp', category='AI agents', tags=['Node.js', 'MCP', 'Geocoding'], icon='network', description='Give AI assistants real-time job search, location-aware queries, and intelligent filtering through the Model Context Protocol.', features=['Structured job-search responses', 'Dynamic location lookup', 'MCP, REST API, CLI, and library interfaces']),
    dict(name='DeepSeek OCR Docker', repo='DeepseekOCR', category='ML systems', tags=['Python', 'Docker', 'CUDA'], icon='scan', description='A containerized DeepSeek-OCR setup for extracting text from images and documents, with GPU acceleration and a Flask API.', features=['Configurable OCR inference', 'Streaming and standard API endpoints', 'Persistent model caching']),
    dict(name='Overleaf MCP', repo='Overleaf-mcp', category='AI agents', tags=['MCP', 'Git', 'Redis'], icon='code', description='Connect AI assistants to Overleaf through Git. Read LaTeX files, inspect document structure, and extract research content.', features=['LaTeX structure parsing', 'Section-level content extraction', 'Redis-backed concurrency management']),
    dict(name='Web Search MCP', repo='Web_search_mcp', category='AI agents', tags=['MCP', 'ChromaDB', 'Docker'], icon='search', description='A modular research stack for web search, content extraction, vector storage, and retrieval-augmented generation.', features=['SearXNG search integration', 'Content extraction and embeddings', 'Semantic retrieval with ChromaDB']),
    dict(name='Universal Report Generator', repo='Universal-Report-Generator', category='Developer tools', tags=['Python', 'Matplotlib', 'HTML'], icon='chart', description='Turn console output, logs, errors, tables, and Matplotlib plots into a single shareable HTML report.', features=['Automatic stdout and stderr capture', 'Tables and plot collection', 'Context-manager integration']),
    dict(name='Kãla AI Task Scheduler', repo='Kala-AI-Task-Scheduler', category='AI agents', tags=['Streamlit', 'ChromaDB', 'LLaMA'], icon='calendar', description='An AI-powered calendar combining event management, semantic search, and natural-language conversations about your schedule.', features=['Multiple calendar views', 'Semantic event search', 'Local LLaMA integration through Ollama']),
    dict(name='SummarizeFlow', repo='SummarizeFlow', category='AI agents', tags=['Python', 'Graphs', 'Streamlit'], icon='network', description='A graph-based, multi-agent file summarizer that turns complex directory structures into organized project summaries.', features=['Graph-based file processing', 'Language-model summaries', 'Structured JSON output']),
    dict(name='PDF Chat', repo='Llama3_pdf_chat', category='AI agents', tags=['Llama3', 'LangChain', 'Ollama'], icon='message', description='Ask questions about your PDFs and get structured answers from local document retrieval and a Llama3-powered assistant.', features=['PDF text extraction', 'Local retrieval pipeline', 'Answers grounded in document snippets']),
    dict(name='YouTube Video Downloader', repo='youtube-downloader', category='Developer tools', tags=['PyQt6', 'yt-dlp', 'FFmpeg'], icon='play', description='A desktop interface for controlling video and audio downloads, from resolution and codec to subtitles and metadata.', features=['Video and audio format selection', 'FFmpeg stream merging', 'Subtitles and metadata options']),
    dict(name='Logger', repo='Logger', category='Developer tools', tags=['Python', 'AST', 'Rich'], icon='terminal', description='Python code analysis and execution monitoring, with static inspection, runtime instrumentation, and readable console reports.', features=['AST-based code analysis', 'Function timing and call statistics', 'Rich console output']),
    dict(name='JSON Visualizer', repo='Json-Visualizer', category='Data tools', tags=['Streamlit', 'Pyvis', 'NetworkX'], icon='network', description='Transform nested JSON into an interactive network graph. Explore relationships, inspect data types, and navigate complex structures.', features=['File upload and pasted input', 'Drag, zoom, and pan', 'Color-coded data types']),
    dict(name='Data Conversion', repo='Data-Conversion', category='Data tools', tags=['Python', 'CSV', 'Parquet'], icon='swap', description='A practical toolkit for tabular data workflows: split large CSVs, convert CSV to Parquet, and inspect Parquet files.', features=['CSV splitting', 'CSV and Parquet conversion', 'Parquet inspection utilities']),
    dict(name='News Bot', repo='News_bot', category='Developer tools', tags=['Python', 'PyQt5', 'NewsAPI'], icon='document', description='A desktop news reader with topic, timeframe, language, and sorting controls, powered by NewsAPI.', features=['Topic-based news queries', 'Language and date filters', 'Desktop reading interface']),
    dict(name='SENSATION Voice Assistant', repo='SENSATION-Voice-assistant', category='ML systems', tags=['Python', 'Vosk', 'pyttsx3'], icon='wave', description='A voice-controlled Python assistant that combines speech recognition and text-to-speech with everyday desktop tasks.', features=['Vosk speech recognition', 'Spoken responses', 'Voice-triggered utilities']),
]

ARTICLES = [
    dict(title='A comprehensive guide to clustering algorithms', subtitle='Mathematical foundations & practical applications', category='Machine learning', format='Article', visual='clusters', url='https://medium.com/@srinjoy.ghosh/a-comprehensive-guide-to-clustering-algorithms-mathematical-foundations-and-practical-applications-f3824a4ff62f', description='From centroid and density methods to graph-based approaches: understand the mathematics, compare trade-offs, and choose an algorithm for your data.'),
    dict(title='Types of quantization', subtitle='Smaller models. Clearer trade-offs.', category='LLM optimization', format='Interactive article', visual='quantization', url='https://ghoshsrinjoy.github.io/Quantization-with-Playgrounds/', description='Explore LLM quantization techniques, change parameters, and visualize their effects on memory, performance, and accuracy.'),
]

LABS = [
    dict(slug='k-means', title='K-Means clustering', short='K-Means', kind='Unsupervised learning', visual='clusters', description='Move from scattered points to structure. Watch centroids and cluster assignments converge, one iteration at a time.', controls='Choose K and a point count, generate a dataset, then run clustering. Change K or regenerate to compare the results.', concepts=['Nearest-centroid assignment using Euclidean distance.', 'Centroid updates using the mean of assigned points.', 'Lloyd’s algorithm, convergence, and sensitivity to initialization.'], note='', height=850),
    dict(slug='pca-dimensionality-reduction', title='PCA dimensionality reduction', short='PCA', kind='Dimensionality reduction', visual='pca', description='Find the directions of maximum variance and see a 3D dataset projected into two dimensions.', controls='Adjust the point count, cluster count, and spread. Generate data, run PCA, and compare the 3D view with its 2D projection.', concepts=['Mean-centering and covariance-matrix computation.', 'Power iteration with deflation to estimate principal components.', 'Explained-variance ratios and projection onto the leading eigenvectors.'], note='', height=1260),
    dict(slug='decision-tree-builder', title='Decision tree builder', short='Decision trees', kind='Supervised learning', visual='tree', description='Build interpretable decision rules from CSV data. Explore splits, impurity, and the path an example takes through a tree.', controls='Use the sample data, paste a CSV, or upload your own. Select a target, adjust the tree settings, and build. Inspect a row or export the model.', concepts=['Greedy CART-style splitting for numeric and categorical features.', 'Gini impurity and entropy for classification; MSE for regression.', 'Depth, sample-count, and gain limits that control tree complexity.'], note='CSV processing happens in your browser. This page does not upload your dataset.', height=1450),
    dict(slug='neural-network-playground', title='Neural network playground', short='Neural networks', kind='Deep learning', visual='network', description='Draw a digit, inspect a prediction, and teach the network. See activations, weights, and gradients change through backpropagation.', controls='Draw a digit, select its label, and add it to the training set. Train or teach the drawing, then inspect the prediction and visualization tabs.', concepts=['784 input values, a configurable ReLU hidden layer, and 10 softmax outputs.', 'Cross-entropy loss, backpropagation, and mini-batch SGD.', 'He/Xavier initialization and a warm start using synthetic digits.'], note='This small educational model is initialized using synthetic digits. Its predictions are demonstrations, not a handwriting-recognition benchmark.', height=1850),
    dict(slug='gradient-descent-visualizer', title='Gradient descent visualizer', short='Gradient descent', kind='Optimization', visual='contour', description='Follow an optimizer across a loss landscape. Compare gradient descent, Momentum, Nesterov, and Adam.', controls='Choose a loss function and optimizer. Click the landscape to set a start, then play or step through the trajectory. Tune the learning rate and momentum.', concepts=['Analytical gradients for quadratic, Rosenbrock, saddle, and Rastrigin functions.', 'Momentum, lookahead updates, and Adam’s bias-corrected moments.', 'Loss curves, contour lines, and the effect of noisy gradients.'], note='', height=1320),
    dict(slug='manifold-learning-visualizer', title='Manifold learning visualizer', short='Manifold learning', kind='Geometric intuition', visual='manifold', description='Explore 3D shapes and illustrative 2D mappings. Use rotation and color to follow how a surface changes under projection.', controls='Choose a dataset and mapping, adjust the sample count and noise, and rotate the original 3D view to explore the geometry.', concepts=['Intrinsic versus extrinsic dimensionality.', 'The intuition behind neighborhoods, geodesic distances, and embeddings.', 'Why nonlinear structure can be lost in a simple projection.'], note='Concept demonstration: the original demo uses handcrafted geometric projections. The Isomap, MDS, spectral, and t-SNE labels are illustrative; these are not numerical implementations of those algorithms.', height=910),
    dict(slug='attention-vizualization', title='Transformer attention', short='Attention', kind='Language models', visual='attention', description='Follow tokens through a query, key, and value pipeline. Compare attention patterns and inspect a token-to-token matrix.', controls='Enter up to 10 tokens or choose an example. Select an attention head and toggle the matrix to compare simulated patterns.', concepts=['Queries, keys, values, and scaled dot-product attention.', 'Row-wise softmax normalization of attention scores.', 'How different attention heads can emphasize different relationships.'], note='Educational simulation: attention patterns and next-token probabilities are illustrative, not outputs from a trained language model.', height=1600),
]

EXTERNAL_LAB = dict(title='Object detection', kind='Computer vision', visual='scan', url='https://ghoshsrinjoy.github.io/object-detect-demo/', description='Explore the original browser-based object-detection demo, hosted on GitHub Pages.')
